### ISSUE TITLE
Dominio del proyecto

### ISSUE THREAD

**Issue by Villanuevand** [frontendev-life/comandos-angular-cli#3]
Necesitamos un dominio para exponer el proyecto. 

Los mejores precios en dominios siempre los he conseguido en [https://www.namecheap.com](https://www.namecheap.com).   Existen dominios de 0.88$ que sería los ideales... (para mi TDC).

Pero debemos tener en cuenta que un dominio es la fachada de nuestro proyecto y si queremos que tenga éxito, debemos invertir en un nombre bueno... 

Como gusto personal,  un dominio `.info` para este proyecto no estaría mal...

**Comment by osnoser1** [comment]
Voy a cerrar este issue ya que tenemos dominio... 😁
